export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILED = 'EDIT_PROFILE_FAILED';
export const UPDATE_UPLOADING = 'UPDATE_UPLOADING';
export const UPDATE_INITIAL = 'UPDATE_INITIAL';

export const PROFILE_LOADING_ACTIVE = 'PROFILE_LOADING_ACTIVE';
export const PROFILE_LOADING_FINISHED = 'PROFILE_LOADING_FINISHED';

export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';

export const CREATEPOST_SUCCESS = 'CREATEPOST_SUCCESS';
export const CREATEPOST_FAILED = 'CREATEPOST_FAILED';

export const GET_ALL_POST = 'REAQUEST_ALL_POST';
export const GET_ALL_POST_FAILED = 'REAQUEST_ALL_POST_FAILED';

export const SEARCH_PET_SUCCESS = 'SEARCH_PET_SUCCESS';
export const SEARCH_PET_FAILED = 'SEARCH_PET_FAILED';
